services:
  - type: web
    name: apex-day-planner
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: BOT_TOKEN
        value: 8758633147:AAHUeHdOuj5nKxbdNuEpZRv-3wGX6wWY96w
      - key: PORT
        value: 8000
